[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json", "msgpack", "uuid"]}
log = "0.4"
env_logger = "0.8"
tiny_dfs = { path = "../lib" }